library(tidyverse)
library(readxl)
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(gapminder)
library(gganimate)


# 1 read excel files in (keeping just data rows from sheet 2&3)
popdata2 <- read_excel("popdata.xls",2,range="A10:IQ56")
popdata3 <- read_excel("popdata.xls",3,range="B10:BB56")

# 2 bind together
popdata <- bind_cols(popdata2,popdata3)

# make column heads
colnames(popdata) <- c("Date", paste0("M-", 0:100), paste0("F-", 0:100), paste0("P-", 0:100))


# convert wide dataset to 3 columns:

popdata <- popdata %>%
        gather("age_sex", "pop", 2:304)       

# split out age_sex to separate columns        
popdatt <- separate(popdata, age_sex, c("sex", "age"), sep = "-")

# Make age numeric & rename date to Year 
popdat <- mutate(popdatt, age = as.numeric(age), Year = year(Date))

# Drop 1st col and put Year 1st. 
popdatf <- select(popdat, Year, age, sex,pop)

# filter sex to remove persons 
m_f <- filter(popdatf,sex !="P")
m_f

# create % column on m_f ***
# 1 make lookup***
m_f2 <- m_f %>% group_by (Year) %>% summarise(erp=sum(pop))
View(m_f2)
# 2 merge on with leftjoin***
m_f3 <- left_join(m_f, m_f2, by="Year")

# make percentage ***

m_f4 <- mutate(m_f3, perc=pop/erp*100)

# graph with gganimate

p1 <- ggplot() +  
        geom_col(data = subset(m_f4, sex == "M"), aes(x = age, y = perc, frame = Year, cumulative = TRUE, fill = sex, color = sex ), position = "identity") + 
        geom_col(data = subset(m_f4, sex == "F"), aes(x = age, y = -perc, frame = Year, cumulative = TRUE, fill = sex, color = sex ), position = "identity") + 
        coord_flip()+
        scale_fill_manual(values = c("darkorange", "skyblue3"))+  
        scale_color_manual(values = c("darkorange", "skyblue3"))+  
        labs(y = "Percent", x = "age", title = "Australian population", subtitle = "1971 - 2016")+  
        scale_x_continuous(breaks = seq(0, 100, 10))+  
        scale_y_continuous(labels = abs(seq(-1, 1, 0.5)), breaks = seq(-1, 1, 0.5))

gganimate(p1, ani.width = 500, ani.height = 500, filename = "C:/Users/atyeo/OneDrive/R data/pyramid.gif")
